name: Rust

on:
  push:
    branches: ['main']
    paths:
      - 'playlist-util/**'
  pull_request:
    branches: ['main']
    paths:
      - 'playlist-util/**'
env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./playlist-util
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
